hda-analyser: don't try to accumulate None
is_conn_active needs to handle the case where
dst_node.amp_vals_in.get_val_db(idx) returns a list containing None.
Assigning None to res[idx] works, but accumulating None in an int with
+= will fail.

Signed-off-by: Torstein Hegge <hegge@resisty.net>
---
Otherwise the graph view for codec 0 from
http://www.alsa-project.org/db/?f=43a12d6c2af3317ad0e347fb9386dad1f43050a7
will fail with
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
on Node 0x22 with
Amp-In vals:  [0x00 0x00] [0x00 0x00] [0x00 0x00] [0x00 0x00] [0x00 0x00] [0x00 0x00] [0x00 0x00]